package gui;

import basics.*;

import javax.swing.*;
import java.awt.*;
import java.text.ParseException;
import java.util.Objects;
import java.util.function.Function;

public class ReleaseView extends JFrame {
    private JPanel panel1;
    private JTextField titleField;
    private JTextField releaseDateField;
    private JTextField formatField;
    private JTextField trackCountField;
    private JCheckBox officialCheckBox;
    private JTextField idField;

    private <T> String strOrDefault(T value, Function<T, String> op) {
        if (value != null)
            return op.apply(value);

        return "(Unset)";
    }

    public ReleaseView(Release release) {
        getContentPane().add(panel1);

        titleField.setEditable(false);
        releaseDateField.setEditable(false);
        formatField.setEditable(false);
        trackCountField.setEditable(false);
        officialCheckBox.setEnabled(false);
        idField.setEditable(false);

        idField.setText(release.getId());
        titleField.setText(strOrDefault(release.getTitle(), String::toString));
        releaseDateField.setText(strOrDefault(release.getReleaseDate(), PartialDate::getIsoDate));
        trackCountField.setText(strOrDefault(release.getTrackCount(), Objects::toString));
        formatField.setText(strOrDefault(release.getFormat(), String::toString));
        officialCheckBox.setSelected(release.isOfficial());

        pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Title:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Release Date:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Format:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Track Count:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label4, gbc);
        titleField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(titleField, gbc);
        releaseDateField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(releaseDateField, gbc);
        formatField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(formatField, gbc);
        trackCountField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(trackCountField, gbc);
        officialCheckBox = new JCheckBox();
        officialCheckBox.setText("Official");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(officialCheckBox, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("ID: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label5, gbc);
        idField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(idField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
